# Generated by Django 2.0.3 on 2018-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('survey', models.CharField(max_length=200)),
                ('nps_score', models.FloatField()),
                ('total_responses', models.IntegerField()),
                ('total_promoters', models.IntegerField()),
                ('total_detractors', models.IntegerField()),
                ('total_neutral', models.IntegerField()),
                ('statistically_significant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('survey_name', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=30)),
                ('question_name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('response', models.CharField(max_length=500)),
            ],
        ),
    ]
