# Generated by Django 2.0.3 on 2018-03-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawresults',
            unique_together={('client', 'survey_name', 'question_name', 'user_id')},
        ),
    ]
