# Generated by Django 2.0.3 on 2018-03-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0003_auto_20180309_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[(-1, 'Negative'), (0, 'Neutral'), (1, 'Positive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('survey_name', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=30)),
                ('question_name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('response', models.CharField(max_length=500)),
                ('ignore', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='commentanalysis',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.CommentCategories'),
        ),
        migrations.AddField(
            model_name='commentanalysis',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.Comments'),
        ),
    ]
