# Generated by Django 2.0.3 on 2018-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0006_auto_20180309_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaggregations',
            name='percent_detractors',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
