# Generated by Django 2.0.3 on 2018-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0007_surveyaggregations_percent_detractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaggregations',
            name='nps_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
