# Generated by Django 2.0.3 on 2018-03-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0009_productaggregations_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaggregations',
            old_name='product',
            new_name='products',
        ),
    ]
