# Generated by Django 2.0.3 on 2018-03-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0010_auto_20180312_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=200)),
                ('academic_year', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('client', models.CharField(max_length=30)),
                ('can_teach', models.BooleanField()),
            ],
        ),
    ]
