# Generated by Django 2.0.3 on 2018-03-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0011_productusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawresults',
            name='can_teach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productusers',
            name='can_teach',
            field=models.BooleanField(default=False),
        ),
    ]
