# Generated by Django 2.0.3 on 2018-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0012_auto_20180314_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAggregations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('survey', models.CharField(max_length=30)),
                ('user_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('nps_score', models.FloatField()),
                ('total_responses', models.IntegerField()),
                ('promoters', models.IntegerField()),
                ('detractors', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('percent_detractors', models.FloatField(blank=True, default=None, null=True)),
                ('percent_promoters', models.FloatField(blank=True, default=None, null=True)),
                ('percent_neutral', models.FloatField(blank=True, default=None, null=True)),
                ('statistically_significant', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AggregatedResults',
        ),
        migrations.DeleteModel(
            name='ProductUsers',
        ),
        migrations.RenameField(
            model_name='productaggregations',
            old_name='total_detractors',
            new_name='detractors',
        ),
        migrations.RenameField(
            model_name='productaggregations',
            old_name='total_neutral',
            new_name='neutral',
        ),
        migrations.RenameField(
            model_name='productaggregations',
            old_name='number_clients_negative',
            new_name='num_clients_negative',
        ),
        migrations.RenameField(
            model_name='productaggregations',
            old_name='number_clients_positive',
            new_name='num_clients_positive',
        ),
        migrations.RenameField(
            model_name='productaggregations',
            old_name='total_promoters',
            new_name='promoters',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='total_detractors',
            new_name='detractors',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='total_neutral',
            new_name='neutral',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='number_clients_negative',
            new_name='num_clients_negative',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='number_clients_positive',
            new_name='num_clients_positive',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='total_promoters',
            new_name='promoters',
        ),
        migrations.RemoveField(
            model_name='productaggregations',
            name='number_clients_neutral',
        ),
        migrations.RemoveField(
            model_name='productaggregations',
            name='percent_clients_neutral',
        ),
        migrations.RemoveField(
            model_name='surveyaggregations',
            name='number_clients_neutral',
        ),
        migrations.RemoveField(
            model_name='surveyaggregations',
            name='percent_clients_neutral',
        ),
        migrations.AddField(
            model_name='productaggregations',
            name='user_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='surveyaggregations',
            name='user_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientaggregations',
            unique_together={('client', 'survey', 'user_type')},
        ),
    ]
