# Generated by Django 2.0.3 on 2018-03-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0013_auto_20180314_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaggregations',
            old_name='survey_name',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='surveyaggregations',
            old_name='survey_name',
            new_name='survey',
        ),
    ]
