# Generated by Django 2.0.3 on 2018-03-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0014_auto_20180314_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaggregations',
            name='nps_score',
            field=models.FloatField(null=True),
        ),
    ]
