# Generated by Django 2.0.3 on 2018-03-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0015_auto_20180314_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeltas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('survey', models.CharField(max_length=30)),
                ('products', models.CharField(max_length=30)),
                ('nps_score', models.FloatField(blank=True, default=None, null=True)),
                ('delta_from_2016', models.FloatField(blank=True, default=None, null=True)),
                ('user_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
