# Generated by Django 2.0.3 on 2018-03-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0016_clientdeltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeltas',
            name='statistically_significant_delta',
            field=models.BooleanField(default=False),
        ),
    ]
