# Generated by Django 2.0.3 on 2018-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0017_clientdeltas_statistically_significant_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeltas',
            name='percent_change_from_2016',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
