# Generated by Django 2.0.3 on 2018-03-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0018_clientdeltas_percent_change_from_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdeltas',
            name='percent_change_from_2016',
        ),
    ]
