# Generated by Django 2.0.3 on 2018-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0019_remove_clientdeltas_percent_change_from_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawresults',
            name='contact_response',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='reason_response',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='recommend_default_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='recommend_response',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='role_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='role_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='survey_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rawresults',
            name='survey_start_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='rawresults',
            name='can_teach',
        ),
        migrations.AlterUniqueTogether(
            name='rawresults',
            unique_together={('client', 'survey_name', 'user_id', 'recommend_response')},
        ),
        migrations.RemoveField(
            model_name='rawresults',
            name='question_name',
        ),
        migrations.RemoveField(
            model_name='rawresults',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='rawresults',
            name='response',
        ),

    ]
