# Generated by Django 2.0.3 on 2018-03-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0020_auto_20180316_1220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawresults',
            unique_together={('client', 'survey_name', 'user_id', 'recommend_response', 'reason_response')},
        ),
    ]
