# Generated by Django 2.0.3 on 2018-03-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0021_auto_20180316_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawresults',
            old_name='role_type',
            new_name='user_type',
        ),
    ]
